spring:
  sendgrid:
    api-key: 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


services:
  internal:
    username: internal
    password: wUrw93cGGYczZKsU

  crm:
    name: crm-service
    url: https://crm-service.herokuapp.com
    username: internal
    password: tinr3kahcuth3gie8bohc4yiXhedcfgx