spring:
  sendgrid:
    api-key: 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

services:
  internal:
    username: internal
    password: wUrw93cGGYczZKsU

  crm:
    name: crm-service
    url: https://crm-service.herokuapp.com
    username: internal
    password: tinr3kahcuth3gie8bohc4yiXhedcfgx